name: My First Workflow

#trigger
on:
- push

#jobs in the workflow
jobs:
 #job name
 my-first-workflow:
    #OS that this workflow will be running on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the context
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}"
    - name: List runner name 
      run: echo "runner os - ${{ runner.os }}"
    #- name: Fail on purpose
      #run: fail()
    - name: echo my secret
      run: echo "mySecret is ${{ secrets.mySecret }}"
    - name: List my current directory before checkout
      run: ls -la
    - name: Checkout the current repo
      uses: actions/checkout@v3
    - name: List my current directory after checkout
      run: ls -la